import {
  LayoutDashboard,
  Users,
  Settings,
  DollarSign,
  ArrowLeftRight,
  Wallet,
  UserCheck,
  Cog,
  Briefcase,
  Send,
} from 'lucide-react';
import type { NavItem } from '../Sidebar';

export const getAdminNavItems = (t: (key: string) => string): NavItem[] => [
  {
    title: t('navigation.dashboard'),
    href: '/dashboard/admin',
    icon: LayoutDashboard,
    description: t('navigation.systemOverview'),
  },
  {
    title: t('navigation.users'),
    href: '/dashboard/admin/users',
    icon: Users,
    description: t('navigation.userManagement'),
    matchSubPaths: true,
  },
  {
    title: t('navigation.providers'),
    href: '/dashboard/admin/providers',
    icon: Briefcase,
    description: t('navigation.providerManagement'),
    matchSubPaths: true,
  },
  {
    title: t('navigation.distributors'),
    href: '/dashboard/admin/distributors',
    icon: UserCheck,
    description: t('navigation.distributorManagement'),
    matchSubPaths: true,
  },
  {
    title: t('admin.navigation.paymentValidators'),
    href: '/dashboard/admin/payment-validators',
    icon: DollarSign,
    description: t('admin.navigation.paymentValidatorsDesc'),
    matchSubPaths: true,
  },
  {
    title: t('admin.navigation.validatorTransfers'),
    href: '/dashboard/admin/validator-transfers',
    icon: Send,
    description: t('admin.navigation.validatorTransfersDesc'),
    matchSubPaths: true,
  },
  {
    title: t('navigation.recharges'),
    href: '/dashboard/admin/recharges',
    icon: Wallet,
    description: t('navigation.rechargeManagement'),
    matchSubPaths: true,
  },
  {
    title: 'Precios',
    href: '/dashboard/admin/pricing',
    icon: Settings,
    description: 'Configuración de markup y fees',
    matchSubPaths: true,
  },
  {
    title: t('navigation.transactions'),
    href: '/dashboard/admin/transactions',
    icon: ArrowLeftRight,
    description: t('navigation.transactionMonitoring'),
    matchSubPaths: true,
  },
  {
    title: 'Configuración',
    href: '/dashboard/admin/settings',
    icon: Cog,
    description: 'Configuración del sistema',
    matchSubPaths: true,
  },
];
