import {
  Stack,
  StackProps,
  CfnOutput,
  RemovalPolicy,
  Duration,
  Tags,
} from "aws-cdk-lib";
import { Construct } from "constructs";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as rds from "aws-cdk-lib/aws-rds";
import * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";
import * as s3 from "aws-cdk-lib/aws-s3";
import * as cloudfront from "aws-cdk-lib/aws-cloudfront";
import * as origins from "aws-cdk-lib/aws-cloudfront-origins";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as logs from "aws-cdk-lib/aws-logs";
import * as iam from "aws-cdk-lib/aws-iam";
import * as cloudwatch from "aws-cdk-lib/aws-cloudwatch";
import * as sns from "aws-cdk-lib/aws-sns";
import * as cloudwatch_actions from "aws-cdk-lib/aws-cloudwatch-actions";
import * as s3deploy from "aws-cdk-lib/aws-s3-deployment";
import * as path from "path";

/**
 * MVP-Optimized Stack for Stream Sales
 *
 * COST OPTIMIZATION STRATEGY:
 * - RDS t4g.micro (free tier 12 months, then ~$15/month)
 * - VPC with VPC Endpoints instead of NAT Gateway (saves ~$32/month)
 * - Lambda + CloudFront for compute (pay-per-use)
 * - Single-AZ RDS (MVP only, can upgrade to Multi-AZ later)
 *
 * ESTIMATED COST: $3-9/month (first 12 months), $18-25/month after
 */

interface MvpStackProps extends StackProps {
  /**
   * Environment name (dev only for MVP)
   */
  environment?: string;
  /**
   * Alarm email for critical notifications (optional)
   */
  alarmEmail?: string;
  /**
   * Whether to use free tier configurations
   */
  useFreeTier?: boolean;
}

export class MvpStack extends Stack {
  public readonly vpc: ec2.IVpc;
  public readonly dbInstance: rds.DatabaseInstance;
  public readonly imagesBucket: s3.Bucket;
  public readonly staticBucket: s3.Bucket;
  public readonly distribution: cloudfront.Distribution;
  public readonly serverFunction: lambda.Function;

  constructor(scope: Construct, id: string, props?: MvpStackProps) {
    super(scope, id, props);

    const env = props?.environment || "dev";
    const useFreeTier = props?.useFreeTier ?? true;

    // ============================================
    // 1. NETWORKING - VPC WITHOUT NAT GATEWAY
    // ============================================
    // Cost optimization: Use VPC Endpoints instead of NAT Gateway
    // NAT Gateway costs ~$32/month, VPC Endpoints cost ~$7/month for S3 + Secrets Manager
    this.vpc = new ec2.Vpc(this, "VPC", {
      maxAzs: 2,
      natGateways: 0, // ⚡ COST SAVE: No NAT Gateway (~$32/month saved)
      subnetConfiguration: [
        {
          name: "Public",
          subnetType: ec2.SubnetType.PUBLIC,
          cidrMask: 24,
        },
        {
          name: "Isolated",
          subnetType: ec2.SubnetType.PRIVATE_ISOLATED, // No internet access
          cidrMask: 24,
        },
      ],
      enableDnsHostnames: true,
      enableDnsSupport: true,
    });

    // VPC Endpoints - cheaper alternative to NAT Gateway for AWS services
    // S3 Gateway Endpoint (FREE)
    this.vpc.addGatewayEndpoint("S3Endpoint", {
      service: ec2.GatewayVpcEndpointAwsService.S3,
      subnets: [{ subnetType: ec2.SubnetType.PRIVATE_ISOLATED }],
    });

    // Secrets Manager Interface Endpoint (~$7/month, but necessary for Lambda)
    this.vpc.addInterfaceEndpoint("SecretsManagerEndpoint", {
      service: ec2.InterfaceVpcEndpointAwsService.SECRETS_MANAGER,
      subnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      privateDnsEnabled: true,
    });

    // ============================================
    // 2. SECRETS MANAGEMENT
    // ============================================
    // Cost: $0.40/month per secret

    // Database credentials will be generated by RDS automatically
    // We'll reference it after RDS creation

    // JWT Secret
    const jwtSecret = new secretsmanager.Secret(this, "JWTSecret", {
      secretName: `stream-sales/${env}/jwt/secret`,
      description: `JWT secret for Stream Sales ${env} environment`,
      generateSecretString: {
        excludePunctuation: true,
        includeSpace: false,
        passwordLength: 64,
      },
      removalPolicy: RemovalPolicy.DESTROY,
    });

    // Encryption key secret
    const encryptionSecret = new secretsmanager.Secret(this, "EncryptionSecret", {
      secretName: `stream-sales/${env}/encryption/key`,
      description: `Encryption key for Stream Sales ${env} environment`,
      generateSecretString: {
        excludePunctuation: true,
        includeSpace: false,
        passwordLength: 64,
      },
      removalPolicy: RemovalPolicy.DESTROY,
    });

    // ============================================
    // 3. DATABASE - RDS PostgreSQL t4g.micro (FREE TIER)
    // ============================================
    // Cost: FREE for 12 months (750 hours/month), then ~$15/month
    // Single-AZ for MVP, can upgrade to Multi-AZ later

    // Security Group for Database
    const dbSecurityGroup = new ec2.SecurityGroup(this, "DatabaseSecurityGroup", {
      vpc: this.vpc,
      description: "Security group for RDS PostgreSQL instance",
      allowAllOutbound: false,
    });

    // RDS Instance - t4g.micro (free tier eligible)
    this.dbInstance = new rds.DatabaseInstance(this, "DatabaseInstance", {
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_15_7, // Latest PostgreSQL 15
      }),
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.T4G, // ARM-based, cheaper and faster
        useFreeTier ? ec2.InstanceSize.MICRO : ec2.InstanceSize.SMALL
      ),
      vpc: this.vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE_ISOLATED, // No internet access
      },
      securityGroups: [dbSecurityGroup],
      credentials: rds.Credentials.fromGeneratedSecret("dbadmin", {
        secretName: `stream-sales/${env}/database/credentials`,
      }),
      databaseName: "streams",
      allocatedStorage: 20, // Minimum for free tier (20-100GB)
      maxAllocatedStorage: 100, // Auto-scaling up to 100GB
      storageType: rds.StorageType.GP3, // Latest generation, better performance
      storageEncrypted: true,
      publiclyAccessible: false,
      multiAz: false, // ⚡ COST SAVE: Single-AZ for MVP (can upgrade later)
      backupRetention: Duration.days(7),
      deleteAutomatedBackups: true,
      deletionProtection: false, // MVP - easy cleanup
      removalPolicy: RemovalPolicy.DESTROY, // MVP - easy cleanup
      autoMinorVersionUpgrade: true,
      enablePerformanceInsights: false, // ⚡ COST SAVE: Disabled for MVP
      cloudwatchLogsExports: [], // ⚡ COST SAVE: No log exports to reduce costs
    });

    // ============================================
    // 4. STORAGE - S3 Buckets
    // ============================================
    // Cost: ~$1-2/month for images + static assets

    // Bucket for user-uploaded images
    this.imagesBucket = new s3.Bucket(this, "ImagesBucket", {
      bucketName: `stream-sales-${env}-images-${this.account}`,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      blockPublicAccess: new s3.BlockPublicAccess({
        blockPublicAcls: false,
        ignorePublicAcls: false,
        blockPublicPolicy: false,
        restrictPublicBuckets: false,
      }),
      publicReadAccess: true,
      cors: [
        {
          allowedMethods: [
            s3.HttpMethods.GET,
            s3.HttpMethods.PUT,
            s3.HttpMethods.POST,
          ],
          allowedOrigins: ["*"], // Can restrict later
          allowedHeaders: ["*"],
          maxAge: 3000,
        },
      ],
      lifecycleRules: [
        {
          id: "DeleteOldMultipartUploads",
          enabled: true,
          abortIncompleteMultipartUploadAfter: Duration.days(7),
        },
      ],
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    // Bucket for static assets (Next.js build output)
    this.staticBucket = new s3.Bucket(this, "StaticBucket", {
      bucketName: `stream-sales-${env}-static-${this.account}`,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL, // CloudFront will access via OAI
      versioned: false,
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    // ============================================
    // 5. COMPUTE - Lambda Function (OpenNext will deploy this)
    // ============================================
    // This is a placeholder - OpenNext will create the actual functions
    // We create this to establish IAM permissions and VPC configuration

    const lambdaRole = new iam.Role(this, "LambdaExecutionRole", {
      assumedBy: new iam.ServicePrincipal("lambda.amazonaws.com"),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName(
          "service-role/AWSLambdaVPCAccessExecutionRole"
        ),
      ],
    });

    // Grant permissions to Lambda
    this.dbInstance.secret!.grantRead(lambdaRole);
    jwtSecret.grantRead(lambdaRole);
    encryptionSecret.grantRead(lambdaRole);
    this.imagesBucket.grantReadWrite(lambdaRole);
    this.staticBucket.grantRead(lambdaRole);

    // Lambda security group
    const lambdaSecurityGroup = new ec2.SecurityGroup(this, "LambdaSecurityGroup", {
      vpc: this.vpc,
      description: "Security group for Lambda functions",
      allowAllOutbound: true,
    });

    // Allow Lambda to connect to RDS
    dbSecurityGroup.addIngressRule(
      lambdaSecurityGroup,
      ec2.Port.tcp(5432),
      "Allow Lambda to connect to RDS"
    );

    // Placeholder Lambda function (OpenNext will replace this)
    this.serverFunction = new lambda.Function(this, "ServerFunction", {
      runtime: lambda.Runtime.NODEJS_18_X,
      handler: "index.handler",
      code: lambda.Code.fromAsset(path.join(__dirname, "../../../.open-next/server-function")),
      timeout: Duration.seconds(30),
      memorySize: 512, // Start small, can increase if needed
      vpc: this.vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
      },
      securityGroups: [lambdaSecurityGroup],
      role: lambdaRole,
      environment: {
        NODE_ENV: env,
        AWS_SECRET_NAME: `stream-sales/${env}/database/credentials`,
        DATABASE_HOST: this.dbInstance.dbInstanceEndpointAddress,
        DATABASE_PORT: this.dbInstance.dbInstanceEndpointPort,
        DATABASE_NAME: "streams",
        JWT_SECRET_ARN: jwtSecret.secretArn,
        ENCRYPTION_SECRET_ARN: encryptionSecret.secretArn,
        IMAGES_BUCKET_NAME: this.imagesBucket.bucketName,
      },
      logRetention: logs.RetentionDays.ONE_WEEK,
    });

    // ============================================
    // 6. CDN - CloudFront Distribution
    // ============================================
    // Cost: ~$1-2/month (50GB free tier)

    // Origin Access Identity for S3
    const oai = new cloudfront.OriginAccessIdentity(this, "OAI", {
      comment: "OAI for Stream Sales static assets",
    });
    this.staticBucket.grantRead(oai);

    // CloudFront distribution
    this.distribution = new cloudfront.Distribution(this, "Distribution", {
      comment: `Stream Sales ${env} Distribution`,
      defaultBehavior: {
        origin: new origins.S3Origin(this.staticBucket, {
          originAccessIdentity: oai,
        }),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
        cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
        compress: true,
      },
      additionalBehaviors: {
        "/api/*": {
          origin: new origins.HttpOrigin(
            `${this.serverFunction.functionName}.lambda-url.${this.region}.on.aws`,
            {
              protocolPolicy: cloudfront.OriginProtocolPolicy.HTTPS_ONLY,
            }
          ),
          viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
          allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
          cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED, // No cache for API
        },
      },
      priceClass: cloudfront.PriceClass.PRICE_CLASS_100, // ⚡ COST SAVE: US, Canada, Europe only
      enableLogging: false, // ⚡ COST SAVE: Disable access logs for MVP
      httpVersion: cloudfront.HttpVersion.HTTP2_AND_3,
      minimumProtocolVersion: cloudfront.SecurityPolicyProtocol.TLS_V1_2_2021,
    });

    // ============================================
    // 5.1 ASSET DEPLOYMENT
    // ============================================
    // Deploy static assets to S3

    const openNextPath = path.join(__dirname, "../../../.open-next");

    new s3deploy.BucketDeployment(this, "StaticAssetsDeployment", {
      sources: [s3deploy.Source.asset(path.join(openNextPath, "assets"))],
      destinationBucket: this.staticBucket,
      distribution: this.distribution,
      distributionPaths: ["/*"],
      memoryLimit: 512, // Save costs on deployment lambda
    });

    // ============================================
    // 7. MONITORING - Basic CloudWatch Alarms (FREE)
    // ============================================
    if (props?.alarmEmail) {
      const alarmTopic = new sns.Topic(this, "AlarmTopic", {
        displayName: `Stream Sales ${env} Alarms`,
      });

      new sns.Subscription(this, "AlarmEmailSubscription", {
        topic: alarmTopic,
        protocol: sns.SubscriptionProtocol.EMAIL,
        endpoint: props.alarmEmail,
      });

      // Database CPU Alarm (free metric)
      const dbCpuAlarm = new cloudwatch.Alarm(this, "DatabaseCPUAlarm", {
        metric: this.dbInstance.metricCPUUtilization({
          period: Duration.minutes(5),
        }),
        threshold: 80,
        evaluationPeriods: 2,
        alarmDescription: "Database CPU is too high",
      });
      dbCpuAlarm.addAlarmAction(new cloudwatch_actions.SnsAction(alarmTopic));

      // Database Storage Alarm
      const dbStorageAlarm = new cloudwatch.Alarm(this, "DatabaseStorageAlarm", {
        metric: this.dbInstance.metricFreeStorageSpace({
          period: Duration.minutes(5),
        }),
        threshold: 2 * 1024 * 1024 * 1024, // 2GB remaining
        evaluationPeriods: 1,
        comparisonOperator: cloudwatch.ComparisonOperator.LESS_THAN_THRESHOLD,
        alarmDescription: "Database storage is running low",
      });
      dbStorageAlarm.addAlarmAction(new cloudwatch_actions.SnsAction(alarmTopic));

      // Lambda Error Alarm
      const lambdaErrorAlarm = new cloudwatch.Alarm(this, "LambdaErrorAlarm", {
        metric: this.serverFunction.metricErrors({
          period: Duration.minutes(5),
        }),
        threshold: 10,
        evaluationPeriods: 1,
        alarmDescription: "Lambda function errors detected",
      });
      lambdaErrorAlarm.addAlarmAction(new cloudwatch_actions.SnsAction(alarmTopic));
    }

    // ============================================
    // 8. TAGS
    // ============================================
    Tags.of(this).add("Project", "StreamSales");
    Tags.of(this).add("Environment", env);
    Tags.of(this).add("ManagedBy", "CDK");
    Tags.of(this).add("CostCenter", "Engineering");
    Tags.of(this).add("Optimization", "MVP-FreeTier");

    // ============================================
    // 9. OUTPUTS
    // ============================================
    new CfnOutput(this, "CloudFrontURL", {
      value: `https://${this.distribution.distributionDomainName}`,
      description: "CloudFront distribution URL",
      exportName: `StreamSales-${env}-CloudFrontURL`,
    });

    new CfnOutput(this, "DatabaseEndpoint", {
      value: this.dbInstance.dbInstanceEndpointAddress,
      description: "RDS instance endpoint",
      exportName: `StreamSales-${env}-DatabaseEndpoint`,
    });

    new CfnOutput(this, "DatabaseSecretArn", {
      value: this.dbInstance.secret!.secretArn,
      description: "ARN of the database credentials secret",
      exportName: `StreamSales-${env}-DatabaseSecretArn`,
    });

    new CfnOutput(this, "JWTSecretArn", {
      value: jwtSecret.secretArn,
      description: "ARN of the JWT secret",
      exportName: `StreamSales-${env}-JWTSecretArn`,
    });

    new CfnOutput(this, "ImagesBucketName", {
      value: this.imagesBucket.bucketName,
      description: "S3 bucket for product images",
      exportName: `StreamSales-${env}-ImagesBucketName`,
    });

    new CfnOutput(this, "StaticBucketName", {
      value: this.staticBucket.bucketName,
      description: "S3 bucket for static assets",
      exportName: `StreamSales-${env}-StaticBucketName`,
    });

    new CfnOutput(this, "DistributionId", {
      value: this.distribution.distributionId,
      description: "CloudFront distribution ID",
      exportName: `StreamSales-${env}-DistributionId`,
    });

    new CfnOutput(this, "LambdaRoleArn", {
      value: lambdaRole.roleArn,
      description: "Lambda execution role ARN (for OpenNext)",
      exportName: `StreamSales-${env}-LambdaRoleArn`,
    });

    // Database connection command
    new CfnOutput(this, "DatabaseConnectCommand", {
      value: `aws secretsmanager get-secret-value --secret-id ${this.dbInstance.secret!.secretArn} --query SecretString --output text | jq -r '"postgresql://\\(.username):\\(.password)@${this.dbInstance.dbInstanceEndpointAddress}:${this.dbInstance.dbInstanceEndpointPort}/streams"'`,
      description: "Command to get database connection string",
    });

    // Cost estimation output
    new CfnOutput(this, "EstimatedMonthlyCost", {
      value: useFreeTier
        ? "$3-9/month (first 12 months with free tier), then $18-25/month"
        : "$18-25/month",
      description: "Estimated monthly AWS costs",
    });
  }
}
